### ISSUE TITLE
lofreq and lofreq3 future

### ISSUE THREAD

**Issue by nekrut** [andreas-wilm/lofreq3#7]
We are considering wrapping lofreq for Galaxy (https://github.com/galaxyproject). I have looked at the github page and it appears that the last release was over two years ago. There are also numerous old issues and a four year old PR.  Are you planning to be updating and supporting lofreq in the future? TX!

**Comment by nekrut** [comment]
hmmm ... based on our in-house testing this is by-far the best tool for pooled viral and bacterial samples. A great improvement from https://www.ncbi.nlm.nih.gov/pubmed/21699709

**Comment by andreas-wilm** [comment]
Hi Anton, I'm very glad to hear you like LoFreq :) 

LoFreq3 is not production ready yet. It's currently a hobby of mine after having left academia. The basic functionality of variant and indel calling is there however. I'll add documentation and a workflow recipe (mixing LoFreq2 preprocessing and LoFreq3 variant calling) next. Niranjan will hopefully over time assign students to the development work. 

Having said this, LoFreq2 is considered stable. All PRs are usage related, i.e. not bugs. Due to limited development time all (my) future focus will be on LoFreq3

Niranjan and I will reply to your email separately

Many thanks, Andreas
